#!/bin/bash

# prune			Prune the image archive
# version		0.0.1
# author		Brian Walter @briantwalter
# description		Simple script to limit the 
#			number of save archive images

# configuration
ARCHDIR=/home/pi/src/pispy/archive
DAYSOLD=8

# main
if [ -d ${ARCHDIR} ]; then
  find ${ARCHDIR} -mtime +${DAYSOLD} | xargs rm -rf > /dev/null 2>&1
fi

